camera:
  stream: 2
  width: 1920 #changing width and height might have undeterminant effects based on the camera
  height: 1080
  model: 'yolo11n' # ./runs/detect/train7/weights/best.pt
  cameraSensorW: 0.00454
  cameraSensorH: 0.00340
  cameraPixelsize: 0.00000314814
  cameraFocalLength: 0.0021
  cameraTilt: 70 #degrees
  useCalib: True
  trimX1: 50
  trimX2: 50
  trimY1: 0
  trimY2: 100

map:
  centerLat: 42.062220
  centerLon: -87.678361

mavLink:
  port: 14445

analyze:
  doDetections: True
  detections: ['car', 'person'] #which objects to detect
  classes: [0, 2] #make sure this corresponds to detections
  colors: ['blues', 'reds']
  waitTime: 5 #seconds
  dataTimeout: 0.5 #seconds
  gpsMount: 12.0 #degrees
  maxAngle: 1.57 #radians
  cleanData: True
  maxDistance: 50 #meters
  minHeight: 5 #meters


groups:
  epsilon: 0.00029
  minSamples: 3
